### ISSUE TITLE
Unable to create Points [Geodata]

### ISSUE THREAD

**Issue by dirkseidensticker** [eScienceCenter/Spacialist#239]
### Steps to reproduce
1. Create new point-object in map-view

### Expected behaviour
New point should be created

### Actual behaviour
Error: `$points must contain at least two entries`

This error message can be traced back to: `/lumen/vendor/phaza/laravel-postgis/src/Geometries/PointCollection.php` Line 23-24 (see as well [PointCollection.php#L23](https://github.com/njbarrett/laravel-postgis/blob/master/src/Geometries/PointCollection.php#L23))

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Lumen Version:**

**Spacialist version:**

**List of activated modules:**
<details>
<summary>Module List</summary>
</details>

**Are you using external storage, if yes which one:** local/ftp/aws/...

### Client configuration
**Browser:**

**Operating system:**

#### Webserver error log
<details>
<summary>Webserver error log</summary>
```
Insert your webserver log here
```
</details>

#### Lumen log (lumen/storage/lumen.log)
<details>
<summary>Lumen log</summary>

```
[2017-06-12 11:44:36] lumen.ERROR: InvalidArgumentException: $points must contain at least two entries in /var/www/html/spacialist/oasen/lumen/vendor/phaza/laravel-postgis/src/Geometries/PointCollection.php:24
Stack trace:
#0 /var/www/html/spacialist/oasen/lumen/app/Http/Controllers/ContextController.php(665): Phaza\LaravelPostgis\Geometries\PointCollection->__construct(Array)
#1 [internal function]: App\Http\Controllers\ContextController->addGeodata(Object(Illuminate\Http\Request))
#2 /var/www/html/spacialist/oasen/lumen/vendor/illuminate/container/Container.php(508): call_user_func_array(Array, Array)
#3 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(743): Illuminate\Container\Container->call(Array, Array)
#4 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(709): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#5 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(683): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\ContextController), 'addGeodata', Array)
#6 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(645): Laravel\Lumen\Application->callControllerAction(Array)
#7 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(625): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#8 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#9 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 /var/www/html/spacialist/oasen/lumen/vendor/tymon/jwt-auth/src/Http/Middleware/RefreshToken.php(40): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /var/www/html/spacialist/oasen/lumen/vendor/illuminate/pipeline/Pipeline.php(137): Tymon\JWTAuth\Http\Middleware\RefreshToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /var/www/html/spacialist/oasen/lumen/vendor/tymon/jwt-auth/src/Http/Middleware/Authenticate.php(32): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/html/spacialist/oasen/lumen/vendor/illuminate/pipeline/Pipeline.php(137): Tymon\JWTAuth\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /var/www/html/spacialist/oasen/lumen/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(780): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(626): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#21 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(529): Laravel\Lumen\Application->handleFoundRoute(Array)
#22 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(783): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#23 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(535): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#24 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(476): Laravel\Lumen\Application->dispatch(NULL)
#25 /var/www/html/spacialist/oasen/lumen/public/index.php(28): Laravel\Lumen\Application->run()
#26 {main}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by v1r0x** [comment]
Works flawlessly on current master. Are you sure there was no problem with mixed up branches (migrations from non-master branch, wrong bower files, ...)?

**Comment by v1r0x** [comment]
I could reproduce your issue on the layers branch. Will look into it.

**Comment by v1r0x** [comment]
Should be fixed on the layers branch.
